[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pixel = "8GTANRAJSDKSWShY8tqf2s98fSeQYqvppAH3eDx7hQ4B"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
